"""refactor roles: simplify UserRole, make EventStaff link to User, make org optional on Event

Revision ID: 53057afda020
Revises: f8a3c9d1e2b4
Create Date: 2026-05-05 18:51:50.200886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53057afda020'
down_revision: Union[str, None] = 'f8a3c9d1e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('check_in_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_attendees_check_in_status'))
        batch_op.drop_index(batch_op.f('idx_attendees_email'))
        batch_op.drop_index(batch_op.f('idx_attendees_is_active'))
        batch_op.drop_index(batch_op.f('idx_attendees_order_item_id'))
        batch_op.drop_index(batch_op.f('idx_attendees_ticket_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_audit_logs_action'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_is_active'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_resource'))
        batch_op.drop_index(batch_op.f('idx_audit_logs_user_id'))

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_email_logs_is_active'))
        batch_op.drop_index(batch_op.f('idx_email_logs_recipient_email'))
        batch_op.drop_index(batch_op.f('idx_email_logs_status'))

    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=False))
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_event_staff_event_id'))
        batch_op.drop_index(batch_op.f('idx_event_staff_is_active'))
        batch_op.drop_index(batch_op.f('idx_event_staff_member_id'))
        batch_op.drop_constraint(batch_op.f('uq_event_staff_event_member_role'), type_='unique')
        batch_op.drop_constraint(batch_op.f('event_staff_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('member_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('registration_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('registration_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_events_is_active'))
        batch_op.drop_index(batch_op.f('idx_events_organization_id'))
        batch_op.drop_index(batch_op.f('idx_events_organization_slug'))
        batch_op.drop_index(batch_op.f('idx_events_start_date'))
        batch_op.drop_index(batch_op.f('idx_events_status'))
        batch_op.drop_index(batch_op.f('idx_events_visibility'))
        batch_op.drop_constraint(batch_op.f('events_organization_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_followers_organization_id'))
        batch_op.drop_index(batch_op.f('idx_followers_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_followers_user_org'), type_='unique')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_members_is_active'))
        batch_op.drop_index(batch_op.f('idx_members_organization_id'))
        batch_op.drop_index(batch_op.f('idx_members_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_members_user_org'), type_='unique')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_order_items_order_id'))
        batch_op.drop_index(batch_op.f('idx_order_items_ticket_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_orders_customer_email'))
        batch_op.drop_index(batch_op.f('idx_orders_event_id'))
        batch_op.drop_index(batch_op.f('idx_orders_is_active'))
        batch_op.drop_index(batch_op.f('idx_orders_order_number'))
        batch_op.drop_index(batch_op.f('idx_orders_payment_status'))
        batch_op.drop_index(batch_op.f('idx_orders_status'))
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('social_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_organizations_is_active'))
        batch_op.drop_index(batch_op.f('idx_organizations_slug'))
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('failure_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('refund_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('refunded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_payments_is_active'))
        batch_op.drop_index(batch_op.f('idx_payments_order_id'))
        batch_op.drop_index(batch_op.f('idx_payments_provider_payment_id'))
        batch_op.drop_index(batch_op.f('idx_payments_status'))
        batch_op.create_index(batch_op.f('ix_payments_provider_payment_id'), ['provider_payment_id'], unique=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_is_active'))
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_user_id'))
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sale_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('sale_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_tickets_event_id'))
        batch_op.drop_index(batch_op.f('idx_tickets_is_active'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tickets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_event_id'), ['event_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('sale_end',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('sale_start',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.create_index(batch_op.f('idx_refresh_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('idx_refresh_tokens_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('revoked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_payment_id'))
        batch_op.create_index(batch_op.f('idx_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_provider_payment_id'), ['provider_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('refunded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('refund_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('failure_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.create_index(batch_op.f('idx_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_organizations_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('social_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.create_index(batch_op.f('idx_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('idx_orders_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_customer_email'), ['customer_email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('cancelled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('confirmed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_order_items_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_items_order_id'), ['order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_members_user_org'), ['user_id', 'organization_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_members_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_followers_user_org'), ['user_id', 'organization_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_followers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_followers_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_events_visibility'), ['visibility'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_organization_slug'), ['organization_id', 'slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('registration_end',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('registration_start',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_staff_member_id_fkey'), 'members', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_event_staff_event_member_role'), ['event_id', 'member_id', 'role'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_event_staff_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_staff_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_event_staff_event_id'), ['event_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('assigned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.drop_column('is_owner')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_email_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_email_logs_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('idx_email_logs_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_resource'), ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_logs_action'), ['action'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendees_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendees_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendees_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendees_check_in_status'), ['check_in_status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('check_in_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
